spring.application.name=delicias-canastra-api
server.port=8082

app.base-url=http://localhost:8082
app.frontend-url=http://localhost:8082

# Configurações para integração com PagBank Checkout
pagbank.api.url=https://sandbox.api.pagbank.com
pagbank.api.key=09cf42bf-e300-4442-b7d2-a79e13151a3a249bebb447879219c7133b5674dc68f8d9f0-e925-4e58-bf85-f77526fd6954
pagbank.api.sandbox=true
pagbank.notification-url=${app.base-url}/api/pagbank/webhook/checkout
pagbank.redirect-url=${app.frontend-url}
pagbank.return-url=${app.frontend-url}
